# load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

package(
    default_visibility = ["//visibility:public"],
)

# pkg_tar(
#     name = "release",
#     extension = "tar.bz2",
#     deps = [
#         "//loopy/common:release",
#     ]
# )